name: "Publish to GitHub Pages"

on:
  push:
    branches: [ main ]

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot Web Export
        uses: firebelley/godot-export@v5.2.1
        with:
          # Direct links for Godot 4.6 Stable
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Folder where the exporter places the web files
          folder: out/web